///////////////////////////////////
// IMPORT SCHEMA AND MODEL
///////////////////////////////////
const { Schema, model } = require("mongoose");

////////////////////////////////////
// CREATE SCHEMA
////////////////////////////////////

const courseSchema = new Schema({
  name: { type: String, required: true, unique: true },
  city: { type: String, required: false },
  tees: {
      black: 
            [{hole: {type: Number},
              par: {type: Number},  
              yardage: {type: Number},
              handicap: {type: Number},
            },
            {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
              handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },   
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: String},
                par: {type: Number},  
                yardage: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: Number},
                par: {type: Number},  
                yardage: {type: Number},
                handicap: {type: Number},
              },
              {hole: {type: String},
                par: {type: Number},  
                yardage: {type: Number},
              },
              {hole: {type: String},
                par: {type: Number},  
                yardage: {type: Number},
              },
            ], 
      blue: [{hole: {type: Number},
        par: {type: Number},  
        yardage: {type: Number},
        handicap: {type: Number},
      },
      {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
        handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },   
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {out: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {in: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
        {tot: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
      ], 
      white: [{hole: {type: Number},
        par: {type: Number},  
        yardage: {type: Number},
        handicap: {type: Number},
      },
      {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
        handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },   
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {out: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {in: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
        {tot: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
      ], 
      red: [{hole: {type: Number},
        par: {type: Number},  
        yardage: {type: Number},
        handicap: {type: Number},
      },
      {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
        handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },   
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {out: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {hole: {type: Number},
          par: {type: Number},  
          yardage: {type: Number},
          handicap: {type: Number},
        },
        {in: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
        {tot: {type: String},
          par: {type: Number},  
          yardage: {type: Number},
        },
      ], 
  },
  
});

////////////////////////////////////
// CREATE MODEL
////////////////////////////////////
const Course = model("courses", courseSchema);

////////////////////////////////////
// EXPORT MODEL
////////////////////////////////////
module.exports = Course;