module.exports = {
    name: "Rusted Rail",
    city: "Crandall, TX",
    tees: {
        blue: 
              [{hole: 1,
                par: 4,  
                yardage: 402,
                handicap: 10,
              },
              {hole: 2,
                  par: 4,  
                  yardage: 390,
                  handicap: 2,
                },
                {hole: 3,
                  par: 5,  
                  yardage: 567,
                  handicap: 4,
                },
                {hole: 4,
                  par: 4,  
                  yardage: 363,
                  handicap: 12,
                },
                {hole: 5,
                  par: 5,  
                  yardage: 573,
                  handicap: 6,
                },
                {hole: 6,
                  par: 4,  
                  yardage: 315,
                handicap: 14,
                },
                {hole: 7,
                  par: 3,  
                  yardage: 162,
                  handicap: 16,
                },   
                {hole: 8,
                  par: 4,  
                  yardage: 369,
                  handicap: 8,
                },
                {hole: 9,
                  par: 3,  
                  yardage: 162,
                  handicap: 18,
                },
                {hole: null,
                  par: 36,  
                  yardage: 3303,
                },
                {hole: 10,
                  par: 4,  
                  yardage: 394,
                  handicap: 9,
                },
                {hole: 11,
                  par: 4,  
                  yardage: 373,
                  handicap: 7,
                },
                {hole: 12,
                  par: 4,  
                  yardage: 441,
                  handicap: 1,
                },
                {hole: 13,
                  par: 3,  
                  yardage: 167,
                  handicap: 17,
                },
                {hole: 14,
                  par: 5,  
                  yardage: 529,
                  handicap: 5,
                },
                {hole: 15,
                  par: 3,  
                  yardage: 197,
                  handicap: 15,
                },
                {hole: 16,
                  par: 5,  
                  yardage: 553,
                  handicap: 11,
                },
                {hole: 17,
                  par: 4,  
                  yardage: 383,
                  handicap: 13,
                },
                {hole: 18,
                  par: 4,  
                  yardage: 430,
                  handicap: 3,
                },
                {hole: null,
                  par: 36,  
                  yardage: 3467,
                },
                {hole: null,
                  par: 72,  
                  yardage: 6770,
                },
              ]} 
            };