// module.exports = {
//     name: "Gleneagles - Queens",
//     city: "Plano, TX",
//     tees: {
//         black: 
//               [{hole: 1,
//                 par: 4,  
//                 yardage: 358,
//                 handicap: 13,
//               },
//               {hole: 2,
//                   par: 3,  
//                   yardage: 176,
//                   handicap: 17,
//                 },
//                 {hole: 3,
//                   par: 5,  
//                   yardage: 564,
//                   handicap: 1,
//                 },
//                 {hole: 4,
//                   par: 3,  
//                   yardage: 165,
//                   handicap: 15,
//                 },
//                 {hole: 5,
//                   par: 4,  
//                   yardage: 417,
//                   handicap: 11,
//                 },
//                 {hole: 6,
//                   par: 4,  
//                   yardage: 416,
//                 handicap: 7,
//                 },
//                 {hole: 7,
//                   par: 4,  
//                   yardage: 394,
//                   handicap: 9,
//                 },   
//                 {hole: 8,
//                   par: 5,  
//                   yardage: 440,
//                   handicap: 5,
//                 },
//                 {hole: 9,
//                   par: 4,  
//                   yardage: 378,
//                   handicap: 3,
//                 },
//                 {hole: "OUT",
//                   par: 36,  
//                   yardage: 3308,
//                 },
//                 {hole: 10,
//                   par: 5,  
//                   yardage: 451,
//                   handicap: 10,
//                 },
//                 {hole: 11,
//                   par: 3,  
//                   yardage: 130,
//                   handicap: 18,
//                 },
//                 {hole: 12,
//                   par: 4,  
//                   yardage: 400,
//                   handicap: 2,
//                 },
//                 {hole: 13,
//                   par: 4,  
//                   yardage: 394,
//                   handicap: 8,
//                 },
//                 {hole: 14,
//                   par: 4,  
//                   yardage: 385,
//                   handicap: 12,
//                 },
//                 {hole: 15,
//                   par: 3,  
//                   yardage: 197,
//                   handicap: 16,
//                 },
//                 {hole: 16,
//                   par: 5,  
//                   yardage: 523,
//                   handicap: 4,
//                 },
//                 {hole: 17,
//                   par: 3,  
//                   yardage: 166,
//                   handicap: 14,
//                 },
//                 {hole: 18,
//                   par: 4,  
//                   yardage: 398,
//                   handicap: 6,
//                 },
//                 {hole: "IN",
//                   par: 35,  
//                   yardage: 3044,
//                 },
//                 {hole: "TOT",
//                   par: 6352,  
//                   yardage: 71,
//                 },
//               ]} 
//             };